Web/Areas/Management/Controllers/HomeController.cs
namespace Web.Areas.Management.Controllers;

[Area("Management")]
// [Authorize]
public class HomeController : Controller
{
    public IActionResult Index()
    {
        return View();
    }
}

Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using Web.Models;

namespace Web.Controllers;

// [Authorize]
public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    [AllowAnonymous]
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Web/Controllers/VoteController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Web.Models;

namespace Web.Controllers;

[Authorize]
public class VoteController : Controller
{
    private readonly IElectionService _electionService;
    private readonly ITokenService _tokenService;
    private readonly IVoteService _voteService;


    public VoteController(IVoteService voteService, IElectionService electionService, ITokenService tokenService)
    {
        _voteService = voteService;
        _electionService = electionService;
        _tokenService = tokenService;
    }

    public async Task<IActionResult> Index()
    {
        var electionId = HttpContext.User.FindFirst("ElectionId")?.Value;
        var election = await _electionService.GetAsync(int.Parse(electionId ?? throw new InvalidOperationException()));
        return View(election);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(VoteViewModel viewModel)
    {
        // handle invalid model state
        if (!ModelState.IsValid)
        {
            var electionId = HttpContext.User.FindFirst("ElectionId")?.Value;
            var election =
                await _electionService.GetAsync(int.Parse(electionId ?? throw new InvalidOperationException()));
            return View(election);
        }

        try
        {
            // get user token
            var sessionToken = HttpContext.User.FindFirst("Token")?.Value;
            await _voteService.VoteAsync(viewModel.Party, sessionToken ?? throw new InvalidOperationException());
        }
        catch (UnauthorizedAccessException)
        {
            // handle session errors
            ModelState.AddModelError("", "Session expired, sign in again.");
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }
        catch (InvalidOperationException)
        {
            // handle session errors
            ModelState.AddModelError("", "Session expired, sign in again.");
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

        return RedirectToAction("Confirmation");
    }


    public async Task<IActionResult> Confirmation()
    {
        // show what vote number the user is
        var VOTE_NUMBER = 12940; // TODO: get from VoteService.VoteAsync
        var voteNumberNearest100 = (VOTE_NUMBER + 50) / 100 * 100;
        ViewBag.VoteNumber = voteNumberNearest100.ToString("N0");

        // logout the user as they have voted now
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return View();
    }
}

Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "About";
    ViewData["Header"] = "Vote on a current election";
}

<p class="govuk-body">
    Use this service to register your vote for a current election which is in-progress.
</p>

<p class="govuk-body">
    You can use this service to:
</p>
<ul class="govuk-list govuk-list--bullet">
    <li>Vote</li>
</ul>

<a asp-controller="Vote" asp-action="Index" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
    Start now
    <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
        <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z"/>
    </svg>
</a>

<h2 class="govuk-heading-l">Before you start</h2>

<p class="govuk-body">
    You'll be asked for your Unique Voter Token. You can find it on the letter sent to you for this election.
</p>

<p class="govuk-body">
    <environment exclude="Production-Booth">
        You must be registered to vote <strong>online</strong> to use this service.
    </environment>
    <environment names="Production-Booth">
        You must be registered to vote <strong>in person</strong> to use this service.
    </environment>
</p>

<a href="https://www.gov.uk/register-to-vote" role="button" draggable="false" class="govuk-button" data-module="govuk-button">
    Register to vote
</a>