Web/Models/VoteViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Web.Models;

public class VoteViewModel
{
    [Required] public string Party { get; set; } = string.Empty;
}

Web/Controllers/ReportsController.cs
using Web.Models;

namespace Web.Controllers;

public class ReportsController : Controller
{
    private readonly IElectionService _electionService;
    private readonly IReportService _reportService;

    public ReportsController(IReportService reportService, IElectionService electionService)
    {
        _reportService = reportService;
        _electionService = electionService;
    }

    public async Task<IActionResult> Index()
    {
        var elections = await _electionService.GetAllAsync();
        return View(elections);
    }


    public async Task<IActionResult> Details(int id)
    {
        // get election
        var election = await _electionService.GetAsync(id);

        // if election doesn't exist, show 404
        if (election == null) return NotFound();

        // get report data for election
        var timeSeriesVotes = _reportService.GetTimeSeriesVotes(id);
        var partyVotes = _reportService.GetPartyVotes(id);
        var totalVotes = await _reportService.GetVoteCount(id);

        // create view model using data
        var reportViewModel = new ReportViewModel
        {
            Election = election,
            TimeSeriesVotes = timeSeriesVotes,
            PartyVotes = partyVotes,
            TotalVotes = totalVotes
        };

        return View(reportViewModel);
    }
}

Web/Controllers/VoteController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Web.Models;

namespace Web.Controllers;

[Authorize]
public class VoteController : Controller
{
    private readonly IElectionService _electionService;
    private readonly ITokenService _tokenService;
    private readonly IVoteService _voteService;


    public VoteController(IVoteService voteService, IElectionService electionService, ITokenService tokenService)
    {
        _voteService = voteService;
        _electionService = electionService;
        _tokenService = tokenService;
    }

    public async Task<IActionResult> Index()
    {
        var electionId = HttpContext.User.FindFirst("ElectionId")?.Value;
        var election = await _electionService.GetAsync(int.Parse(electionId ?? throw new InvalidOperationException()));
        return View(election);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Index(VoteViewModel viewModel)
    {
        // handle invalid model state
        if (!ModelState.IsValid)
        {
            var electionId = HttpContext.User.FindFirst("ElectionId")?.Value;
            var election =
                await _electionService.GetAsync(int.Parse(electionId ?? throw new InvalidOperationException()));
            return View(election);
        }

        try
        {
            // get user token
            var sessionToken = HttpContext.User.FindFirst("Token")?.Value;
            await _voteService.VoteAsync(viewModel.Party, sessionToken ?? throw new InvalidOperationException());
        }
        catch (UnauthorizedAccessException)
        {
            // handle session errors
            ModelState.AddModelError("", "Session expired, sign in again.");
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }
        catch (InvalidOperationException)
        {
            // handle session errors
            ModelState.AddModelError("", "Session expired, sign in again.");
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        }

        return RedirectToAction("Confirmation");
    }


    public async Task<IActionResult> Confirmation()
    {
        // show what vote number the user is
        var VOTE_NUMBER = 12940; // TODO: get from VoteService.VoteAsync
        var voteNumberNearest100 = (VOTE_NUMBER + 50) / 100 * 100;
        ViewBag.VoteNumber = voteNumberNearest100.ToString("N0");

        // logout the user as they have voted now
        await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
        return View();
    }
}

Web/Views/Vote/Confirmation.cshtml
@{
    ViewData["Title"] = "Vote registered";
}

<div class="govuk-panel govuk-panel--confirmation">
    <h1 class="govuk-panel__title">
        Vote registered
    </h1>
    <div class="govuk-panel__body">
        You are voter<br><strong>~@(ViewBag.VoteNumber)</strong>
    </div>
</div>

<h2 class="govuk-heading-m">What happens next</h2>

<p class="govuk-body">
    Your vote has been registered successfully and it will be included in the count.
</p>

<p class="govuk-body">
    You can view live statistics for this election on our election public reports.
</p>

<a asp-controller="Reports" asp-action="Index" role="button" draggable="false" class="govuk-button govuk-button--start" data-module="govuk-button">
    View reports
    <svg class="govuk-button__start-icon" xmlns="http://www.w3.org/2000/svg" width="17.5" height="19" viewBox="0 0 33 40" aria-hidden="true" focusable="false">
        <path fill="currentColor" d="M0 0h13l20 20-20 20H0l20-20z"/>
    </svg>
</a>

Web/Views/Vote/Index.cshtml
@model Election

@{
    ViewData["Title"] = "Vote";
}

<form asp-action="Index" method="post">
    <div class="govuk-form-group @(ViewData.ModelState.Count > 0 ? "govuk-form-group--error" : "")">
        <fieldset class="govuk-fieldset">
            <legend class="govuk-fieldset__legend govuk-fieldset__legend--l">
                <h1 class="govuk-fieldset__heading">
                    What party do you want to vote for?
                </h1>
            </legend>


            @foreach (var error in ViewData.ModelState.Values)
            {
                @foreach (var error2 in error.Errors)
                {
                    <p class="govuk-error-message">
                        <span class="govuk-visually-hidden">Error:</span> @error2.ErrorMessage
                    </p>
                }
            }

            <div class="govuk-radios" data-module="govuk-radios">
                @foreach (var party  in Model.Parties)
                {
                    <div class="govuk-radios__item">
                        <input class="govuk-radios__input" id="party-@party.Id" name="Party" type="radio" value="@party.Id">
                        <label class="govuk-label govuk-radios__label" for="party-@party.Id">
                            @party.Name
                        </label>
                    </div>
                }
            </div>
        </fieldset>
    </div>

    <button class="govuk-button" data-module="govuk-button">
        Confirm vote
    </button>
</form>